/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YangiliklarRouteImport } from './routes/yangiliklar'
import { Route as SavatchaRouteImport } from './routes/savatcha'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FiliallarRouteImport } from './routes/filiallar'
import { Route as DorilarRouteImport } from './routes/dorilar'
import { Route as BuyurtmalarimRouteImport } from './routes/buyurtmalarim'
import { Route as IndexRouteImport } from './routes/index'

const YangiliklarRoute = YangiliklarRouteImport.update({
  id: '/yangiliklar',
  path: '/yangiliklar',
  getParentRoute: () => rootRouteImport,
} as any)
const SavatchaRoute = SavatchaRouteImport.update({
  id: '/savatcha',
  path: '/savatcha',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FiliallarRoute = FiliallarRouteImport.update({
  id: '/filiallar',
  path: '/filiallar',
  getParentRoute: () => rootRouteImport,
} as any)
const DorilarRoute = DorilarRouteImport.update({
  id: '/dorilar',
  path: '/dorilar',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyurtmalarimRoute = BuyurtmalarimRouteImport.update({
  id: '/buyurtmalarim',
  path: '/buyurtmalarim',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buyurtmalarim': typeof BuyurtmalarimRoute
  '/dorilar': typeof DorilarRoute
  '/filiallar': typeof FiliallarRoute
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/register': typeof RegisterRoute
  '/savatcha': typeof SavatchaRoute
  '/yangiliklar': typeof YangiliklarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buyurtmalarim': typeof BuyurtmalarimRoute
  '/dorilar': typeof DorilarRoute
  '/filiallar': typeof FiliallarRoute
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/register': typeof RegisterRoute
  '/savatcha': typeof SavatchaRoute
  '/yangiliklar': typeof YangiliklarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buyurtmalarim': typeof BuyurtmalarimRoute
  '/dorilar': typeof DorilarRoute
  '/filiallar': typeof FiliallarRoute
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/register': typeof RegisterRoute
  '/savatcha': typeof SavatchaRoute
  '/yangiliklar': typeof YangiliklarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buyurtmalarim'
    | '/dorilar'
    | '/filiallar'
    | '/login'
    | '/profil'
    | '/register'
    | '/savatcha'
    | '/yangiliklar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buyurtmalarim'
    | '/dorilar'
    | '/filiallar'
    | '/login'
    | '/profil'
    | '/register'
    | '/savatcha'
    | '/yangiliklar'
  id:
    | '__root__'
    | '/'
    | '/buyurtmalarim'
    | '/dorilar'
    | '/filiallar'
    | '/login'
    | '/profil'
    | '/register'
    | '/savatcha'
    | '/yangiliklar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuyurtmalarimRoute: typeof BuyurtmalarimRoute
  DorilarRoute: typeof DorilarRoute
  FiliallarRoute: typeof FiliallarRoute
  LoginRoute: typeof LoginRoute
  ProfilRoute: typeof ProfilRoute
  RegisterRoute: typeof RegisterRoute
  SavatchaRoute: typeof SavatchaRoute
  YangiliklarRoute: typeof YangiliklarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yangiliklar': {
      id: '/yangiliklar'
      path: '/yangiliklar'
      fullPath: '/yangiliklar'
      preLoaderRoute: typeof YangiliklarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savatcha': {
      id: '/savatcha'
      path: '/savatcha'
      fullPath: '/savatcha'
      preLoaderRoute: typeof SavatchaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filiallar': {
      id: '/filiallar'
      path: '/filiallar'
      fullPath: '/filiallar'
      preLoaderRoute: typeof FiliallarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dorilar': {
      id: '/dorilar'
      path: '/dorilar'
      fullPath: '/dorilar'
      preLoaderRoute: typeof DorilarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyurtmalarim': {
      id: '/buyurtmalarim'
      path: '/buyurtmalarim'
      fullPath: '/buyurtmalarim'
      preLoaderRoute: typeof BuyurtmalarimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuyurtmalarimRoute: BuyurtmalarimRoute,
  DorilarRoute: DorilarRoute,
  FiliallarRoute: FiliallarRoute,
  LoginRoute: LoginRoute,
  ProfilRoute: ProfilRoute,
  RegisterRoute: RegisterRoute,
  SavatchaRoute: SavatchaRoute,
  YangiliklarRoute: YangiliklarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
